server:
  port: 8058

Spring:
  application:
    name: ClashZone

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-slq: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000